README.md, pkg/cli/commands.go, pkg/cli/info.go, pkg/cli/walletcommands.go
=> Remove the need to sync the wallet manually

pkg/eventmon/logger/logger.go, pkg/eventmon/logger/logger_test.go, pkg/eventmon/monitor/monitor.go
Fixes #34. After the log hook fires, logrus continues to use the `*log.Entry` for other stuff. As the `LogProcessor` formats this `*log.Entry` once received, this can cause a race condition. So instead, we format the entry inside of the hook, and send over the bytes.
=> Fix race condition in event monitoring package

pkg/core/consensus/timer.go, pkg/core/consensus/timer_test.go
=> Fix timer doubling bug

pkg/core/consensus/user/keys.go, pkg/core/consensus/user/keys_test.go
=> Retry random key generation, in case of EOF

pkg/crypto/readme.md
=> Remove crypto package

pkg/core/chain/chain.go
=> Update chain to sync committee with consensus committees on launch

pkg/core/consensus/agreement/agreement_in_test.go, pkg/core/consensus/agreement/broker.go, pkg/core/consensus/agreement/collector.go
=> Increment agreement step counter when receiving a nil voteset

pkg/core/verifiers/transaction.go, pkg/gql/query/blocks.go, pkg/gql/query/mempool.go, pkg/wallet/transactions/bidtx.go, pkg/wallet/transactions/coinbasetx.go, pkg/wallet/transactions/interfaces.go, pkg/wallet/transactions/marshalling_test.go, pkg/wallet/transactions/staketx.go, pkg/wallet/transactions/standardtx.go, pkg/wallet/transactions/timelock.go, pkg/wallet/wallet.go
=> Return Standard as a pointer, instead of a value

harness/engine/profiles.go, pkg/cli/walletcommands.go, pkg/core/transactor/commands.go, pkg/core/transactor/listener.go, pkg/util/nativeutils/rpcbus/methods.go, pkg/wallet/database/database.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go
Fixes for
-  #110 
-  #108 
-  #107
=> Wallet issues

pkg/p2p/peer/peer.go, pkg/p2p/peer/peer_test.go, pkg/p2p/peer/processing/ponger.go, pkg/p2p/peer/router.go
=> Implement ping loop

pkg/gql/README.md, pkg/gql/query/transactions.go, pkg/gql/query/transactions_test.go
=> gql: Support for fetching last N transactions

launch/testnet/main.go, pkg/config/loader.go, pkg/config/loader_test.go, pkg/config/samples/custom.toml
Fixes https://github.com/dusk-network/dusk-blockchain/issues/139
=> Config load accepts secondary registry

pkg/cli/cli.go, pkg/cli/info.go, pkg/cli/walletcommands.go, pkg/core/transactor/commands.go, pkg/core/transactor/listener.go, pkg/core/transactor/transactor.go, pkg/util/nativeutils/rpcbus/methods.go
=> Add command to show loaded wallet address

go.mod, go.sum, pkg/core/consensus/generation/score/factory.go, pkg/core/consensus/initiator/initiator.go, pkg/core/database/heavy/transactions.go, pkg/core/database/interfaces.go, pkg/core/database/lite/transactions.go, pkg/core/transactor/commands.go, pkg/core/transactor/listener.go, pkg/core/verifiers/transaction.go, pkg/core/verifiers/transaction_test.go
Fixes #147 
Updates `dusk-wallet` from v0.1.2 to v1.0.1.
=> Refuse transactions which contain locked inputs

pkg/core/consensus/reduction/firststep/reducer.go, pkg/core/consensus/reduction/firststep/reduction_test.go, pkg/core/consensus/reduction/secondstep/reducer.go, pkg/core/consensus/reduction/secondstep/reduction_test.go
=> Only double reduction timers on failure to converge on a value

Makefile, pkg/core/chain/candidate/blockgenerator.go, pkg/core/chain/candidate/testutil.go, pkg/core/mempool/hashmap.go, pkg/core/mempool/hashmap_test.go, pkg/core/mempool/interface.go, pkg/core/mempool/mempool.go, pkg/core/mempool/mempool_test.go, pkg/util/nativeutils/rpcbus/methods.go
Fixes:
- https://github.com/dusk-network/dusk-blockchain/issues/165
- https://github.com/dusk-network/dusk-blockchain/issues/167
- https://github.com/dusk-network/dusk-blockchain/issues/168
- https://github.com/dusk-network/dusk-blockchain/issues/169
=> Feature mempool refactor

harness/engine/utils.go, harness/tests/localnet_test.go
Ref: https://github.com/dusk-network/dusk-blockchain/issues/186
=> SendQuery new decoding

pkg/core/database/heavy/transactions.go, pkg/core/database/interfaces.go, pkg/core/database/lite/transactions.go, pkg/core/database/testing/drivers_test.go, pkg/core/database/testing/utils.go, pkg/core/database/utils/search.go, pkg/gql/README.md, pkg/gql/query/blocks.go, pkg/gql/query/blocks_test.go, pkg/gql/query/query_test.go, pkg/gql/query/transactions.go, pkg/gql/query/transactions_test.go, pkg/gql/query/types.go
Fixes:
- https://github.com/dusk-network/dusk-explorer/issues/21
- https://github.com/dusk-network/dusk-explorer/issues/25
- https://github.com/dusk-network/dusk-explorer/issues/7
=> Graphql fields

pkg/core/chain/candidate/blockgenerator.go, pkg/core/chain/candidate/testutil.go, pkg/core/chain/chain.go, pkg/core/consensus/agreement/agreement.go, pkg/core/consensus/component.go, pkg/core/consensus/eventprocessor.go, pkg/core/consensus/eventprocessor_test.go, pkg/core/consensus/generation/generator.go, pkg/core/consensus/generation/score/generator.go, pkg/core/consensus/msg/validation.go, pkg/core/consensus/readme.md, pkg/core/consensus/reduction/firststep/reducer.go, pkg/core/consensus/reduction/reduction_test.go, pkg/core/consensus/reduction/secondstep/reducer.go, pkg/core/consensus/reduction/testutil.go, pkg/core/consensus/round.go, pkg/core/consensus/selection/selector.go, pkg/core/consensus/selection/testutil.go, pkg/p2p/peer/handshake.go, pkg/p2p/peer/peer.go, pkg/p2p/peer/peer_test.go, pkg/p2p/peer/processing/frame.go, pkg/p2p/peer/processing/frame_test.go, pkg/p2p/peer/processing/gossip.go, pkg/p2p/peer/processing/gossip_test.go, pkg/p2p/wire/checksum/checksum.go, pkg/p2p/wire/checksum/checksum_test.go, pkg/util/nativeutils/eventbus/eventbus_test.go, pkg/util/nativeutils/eventbus/mock.go
=> Substitute Ed25519 message signing and verification for Blake2b checksums

pkg/core/transactor/listener.go, pkg/core/transactor/transactor.go, pkg/rpc/README.md, pkg/rpc/commands.go, pkg/util/nativeutils/rpcbus/methods.go
=> Add/implement RPC commands

go.mod, go.sum, harness/engine/utils.go, harness/tests/localnet_test.go, pkg/config/samples/default.dusk.toml, pkg/core/consensus/maintainer/maintainer_test.go, pkg/core/transactor/listener.go, pkg/core/transactor/transactor.go, pkg/rpc/README.md, pkg/rpc/commands.go, pkg/rpc/handler.go, pkg/util/nativeutils/rpcbus/methods.go
These changes will prep the RPC server to integrate with `dusk-wallet-cli` more easily.
Fixes #202, fixes #203, fixes #204
=> Minor updates to the RPC server

README.md, launch/start-node/README.md, launch/start-node/start-node.go, launch/testnet/start-node.sh
=> Add a bash script, and an executable, for launching both the blind bid and the node at the same time

pkg/core/transactor/listener.go, pkg/core/transactor/transactor.go, pkg/rpc/commands.go, pkg/util/nativeutils/rpcbus/methods.go
=> Add a JSON-RPC command to inquire whether or not the wallet is loaded

pkg/core/chain/chain.go, pkg/core/chain/collectors.go, pkg/p2p/peer/processing/chainsync/sync.go, pkg/p2p/peer/processing/chainsync/sync_test.go, pkg/p2p/wire/topics/topics.go, pkg/rpc/commands.go, pkg/util/nativeutils/rpcbus/methods.go
=> Add support for fetching synchronization progress as a percentage

README.md, pkg/config/groups.go, pkg/config/loader.go, pkg/config/samples/default.dusk.toml, pkg/core/consensus/initiator/initiator.go, pkg/core/consensus/maintainer/maintainer.go, pkg/core/consensus/maintainer/maintainer_test.go, pkg/core/transactor/listener.go, pkg/core/transactor/transactor.go, pkg/rpc/commands.go, pkg/util/nativeutils/rpcbus/methods.go
=> Make maintainer launch optional instead of mandatory

go.mod, go.sum, pkg/core/chain/chain.go
=> Fix sync percentage, update dusk-wallet import

pkg/rpc/README.md
=> Complete JSON-RPC documentation

pkg/core/consensus/agreement/event.go, pkg/core/marshalling/block.go, pkg/core/marshalling/transactions.go, pkg/p2p/peer/peermsg/getblocks.go, pkg/p2p/wire/encoding/vardata.go
=> Add length check when decoding data of variable size

go.mod, go.sum
This fixes any potential issues that users may have when viewing their balance or transaction history.
=> Update to dusk-wallet v1.1.3

pkg/config/loader.go, pkg/core/mempool/mempool_test.go, pkg/p2p/peer/peermsg/inventory.go, pkg/p2p/peer/peermsg/inventory_test.go
=> Enforce an item limit on inv messages

pkg/core/chain/chain.go, pkg/core/consensus/candidate/blockgenerator.go, pkg/core/verifiers/transaction.go
=> Ensure coinbase on first intermediate block is deterministic

pkg/core/mempool/hashmap.go, pkg/core/mempool/hashmap_test.go, pkg/core/mempool/interface.go, pkg/core/mempool/mempool.go, pkg/core/mempool/mempool_test.go, pkg/rpc/README.md, pkg/rpc/commands.go, pkg/util/nativeutils/rpcbus/methods.go
=> Add functionality for getting a view of the mempool, with certain filters

pkg/config/loader_test.go, pkg/config/samples/default.dusk.toml
=> Default log level to debug

pkg/core/mempool/mempool.go
=> Look up tx by key when requested through `GetMempoolTxs`

launch/testnet/server.go, pkg/rpc/commands.go, pkg/rpc/handler.go, pkg/rpc/rpcserver.go
=> Modularise RPC server

pkg/core/consensus/user/sortition.go, pkg/core/consensus/user/sortition_test.go
=> Avoid range-loop based panic in sortition

pkg/core/database/heavy/transactions.go, pkg/core/database/lite/database.go, pkg/core/database/lite/transactions.go, pkg/core/database/testing/drivers_test.go
=> Complete unimplented functions in the lite database

go.mod, go.sum, pkg/core/chain/chain.go, pkg/core/chain/chain_test.go, pkg/core/database/heavy/transactions.go, pkg/core/database/interfaces.go, pkg/core/database/lite/transactions.go, pkg/core/database/testing/drivers_test.go, pkg/core/transactor/listener.go, pkg/core/transactor/transactor.go, pkg/rpc/README.md, pkg/rpc/commands.go, pkg/util/nativeutils/rpcbus/methods.go
Fixes #223, fixes #189 (through updating wallet version)
=> Add functionality for rebuilding the chain

pkg/p2p/peer/peer.go, pkg/p2p/peer/peer_in_test.go, pkg/p2p/peer/peer_test.go
=> Only send ping message after 30 seconds of inactivity

pkg/core/candidate/broker.go, pkg/core/candidate/broker_test.go, pkg/core/candidate/store.go, pkg/core/candidate/validator.go, pkg/core/mempool/mempool.go, pkg/p2p/peer/router.go, pkg/util/nativeutils/republisher/republisher.go
Fixes #263, fixes #264, fixes #267
=> Fix race condition between validating a candidate hash, and accepting a candidate block

pkg/p2p/peer/processing/chainsync/sync.go
=> Unmarshal incoming block before propagating it over the event bus

pkg/core/database/testing/drivers_test.go, pkg/core/mempool/mempool_test.go
=> Fix intermittent failures on TestFetchDecoys and TestMempoolView

go.mod, go.sum, harness/engine/node.go, harness/engine/profiles.go, harness/engine/utils.go, pkg/config/groups.go, pkg/config/samples/default.dusk.toml, pkg/gql/README.md, pkg/gql/httpserver.go, pkg/gql/httpserver_test.go, pkg/gql/notifications/README.md, pkg/gql/notifications/broker.go, pkg/gql/notifications/broker_test.go, pkg/gql/notifications/client.go, pkg/gql/notifications/messages.go, pkg/gql/notifications/pool.go, pkg/gql/notifications/pool_test.go
=> Extend graphql service to satisfy dusk-explorer back-end needs

pkg/p2p/peer/processing/chainsync/sync.go, pkg/p2p/peer/processing/chainsync/sync_test.go
=> send block instead of bytes.Buffer from chain synchronizer

pkg/util/nativeutils/rpcbus/rpcbus.go
Fixes the random panics reported in https://github.com/dusk-network/dusk-blockchain/issues/310
=> RPCBus should not close request channels

pkg/p2p/peer/peer.go, pkg/p2p/peer/peer_in_test.go, pkg/p2p/peer/processing/gossip.go, pkg/p2p/peer/responding/blockhashbroker.go, pkg/p2p/wire/checksum/checksum.go, pkg/p2p/wire/checksum/checksum_test.go
=> Peer reader handles invalid frames

pkg/core/consensus/initiator/initiator.go
=> Correct faulty typecast in the initiator

pkg/core/consensus/generation/score/generator_test.go, pkg/core/consensus/initiator/initiator.go, pkg/core/consensus/maintainer/maintainer_test.go, pkg/core/database/heavy/README.md, pkg/core/database/heavy/transactions.go, pkg/core/database/interfaces.go, pkg/core/database/lite/transactions.go, pkg/core/database/testing/drivers_test.go, pkg/core/transactor/listener.go
=> Add support for having multiple bid values in the db

pkg/core/consensus/candidate/blockgenerator.go, pkg/core/consensus/candidate/testutil.go
=> Append mempool txs to candidate txs, instead of replacing the slice

pkg/core/consensus/user/provisioners.go, pkg/core/consensus/user/provisioners_test.go, pkg/core/consensus/user/sortition.go, pkg/core/consensus/user/sortition_test.go
=> Fix out of bounds error in sortition

pkg/core/chain/chain.go, pkg/core/chain/chain_test.go
=> Assert certificate message type as message.Certificate

go.mod, go.sum, pkg/core/tests/helper/transactions.go
=> Bump wallet version to v2.0.2

pkg/core/chain/chain.go
=> perform the correct type assertion on incoming 'RoundResults' messages

pkg/p2p/peer/responding/candidatebroker.go, pkg/p2p/peer/responding/candidatebroker_test.go
=> perform correct type assertion for response from GetCandidate

pkg/p2p/peer/processing/chainsync/sync.go
With the introduction of interface{} based message passing
in the RPCBus, unmarshalling the received block into the `blk` variable
caused a mutation in its underlying slices. This affected future verification
as the data was no longer consistent. Fixes #331
=> Unmarshal block buffer into a separate block

pkg/core/consensus/component.go, pkg/core/consensus/generation/score/generator.go, pkg/core/consensus/selection/handler.go, pkg/core/consensus/selection/selector.go, pkg/util/nativeutils/eventbus/listener.go, pkg/util/nativeutils/eventbus/multicaster.go
Fixes #335, and a variety of other race conditions.
=> Fix a variety of race conditions in the codebase

pkg/core/candidate/broker.go, pkg/core/candidate/store.go, pkg/core/chain/chain.go
=> Keep track of republished candidates separately from the queue

harness/README.md, harness/engine/network.go, harness/engine/node.go, harness/engine/profiles.go, harness/engine/utils.go, harness/tests/localnet_test.go
Fixes https://github.com/dusk-network/dusk-blockchain/issues/287
=> Harness refactor

launch/testnet/server.go, pkg/config/groups.go, pkg/config/samples/default.dusk.toml, pkg/gql/httpserver.go, pkg/gql/httpserver_test.go, pkg/rpc/example_test.go, pkg/rpc/interceptors.go, pkg/rpc/server.go
Handles:
https://github.com/dusk-network/dusk-blockchain/issues/291
https://github.com/dusk-network/dusk-blockchain/issues/296
=> gRPC additions

pkg/p2p/kadcast/network.go, pkg/p2p/kadcast/utils.go, pkg/p2p/kadcast/utils_test.go
=> Kadcast tcpframe

cmd/voucher/action.go, cmd/voucher/challenge.go, cmd/voucher/flags.go, cmd/voucher/main.go, cmd/voucher/store.go, cmd/voucher/utils.go
* add initial impl for voucher
=> migrate seeder to cmd/seeder and fix related issues #373 

go.mod, go.sum, pkg/core/data/transactions/fixtures.go, pkg/core/data/transactions/phoenix.go, pkg/core/data/transactions/phoenix_test.go
This follows dusk-network/dusk-protobuf#69
=> synced transaction input definition with protobuf specifications

pkg/core/consensus/candidate/factory.go, pkg/core/consensus/candidate/testutil.go, pkg/core/consensus/factory/factory.go, pkg/core/consensus/initiator/initiator.go, pkg/core/transactor/listener.go
Fixes #457 
Note that this was branched off of `coinbase`
=> Reinstate the consensus initiator

README.md, cmd/wallet/conf/config.go, cmd/wallet/prompt/prompt.go, cmd/wallet/prompt/transfer.go, go.mod, go.sum, pkg/core/chain/mock.go, pkg/core/consensus/candidate/readme.md, pkg/core/consensus/maintainer/maintainer.go, pkg/core/data/database/database_test.go, pkg/core/data/wallet/wallet.go, pkg/core/database/heavy/transactions.go, pkg/core/database/interfaces.go, pkg/core/database/lite/transactions.go
=> Remove all references of ristretto (leave just those commented out for reference)

pkg/core/transactor/funcs.go
=> Create keys when creating wallet

cmd/dusk/server.go, pkg/core/transactor/funcs.go, pkg/core/transactor/listener.go, pkg/core/transactor/transactor.go
=> Create a wallet from the given seed, when calling CreateFromSeed

cmd/dusk/server.go, pkg/core/transactor/funcs.go, pkg/core/transactor/listener.go, pkg/core/transactor/transactor.go
=> Get balance from a Rusk call

.travis.yml, Makefile
Should fix #279 
This takes about 3 minutes off of the unit test job
=> Allow multithreading during unit tests

pkg/core/consensus/bidautomaton/bidautomaton_test.go, pkg/core/consensus/stakeautomaton/stakeautomaton_test.go
=> Fix race conditions that might occur when registering on the RPCBus during maintainer tests

harness/tests/node/rpc_mock_test.go, pkg/core/candidate/broker_test.go, pkg/core/candidate/store_test.go, pkg/core/candidate/validator_test.go, pkg/core/chain/chain_test.go, pkg/core/consensus/agreement/accumulator_test.go, pkg/core/consensus/candidate/generation_test.go, pkg/core/consensus/candidate/genesis_test.go, pkg/core/consensus/reduction/firststep/aggregator_test.go, pkg/core/data/transactions/serialization_test.go, pkg/core/mempool/mempool_test.go, pkg/gql/httpserver_test.go, pkg/gql/query/query_test.go, pkg/p2p/kadcast/network_test.go, pkg/p2p/kadcast/utils_test.go, pkg/p2p/peer/peer_in_test.go, pkg/util/nativeutils/eventbus/eventbus_test.go, pkg/util/nativeutils/eventbus/mock.go
=> No test logging

cmd/dusk/server.go, pkg/config/groups.go, pkg/config/samples/default.dusk.toml, pkg/core/chain/chain.go, pkg/core/consensus/candidate/genesis_test.go, pkg/core/consensus/generation/score/generator.go, pkg/core/consensus/selection/handler.go, pkg/core/data/transactions/provider.go, pkg/core/mempool/mempool.go, pkg/p2p/peer/processing/chainsync/sync_test.go
Also add configuration parameter for the timeout
=> Move all deadline cancellations from components to transactions/provider

cmd/utils/metrics/api.go, cmd/utils/metrics/metrics.go
=> fix GQL query for mempool transaction count

Makefile, cmd/utils/main.go, cmd/utils/walletutils/wallet.go, devnet.sh, go.mod, harness/tests/localnet_test.go, pkg/core/data/wallet/seed.go, pkg/p2p/kadcast/packet.go, scripts/build.go
This PR addresses having the devnet.sh scrips usable with dusk blindbid. I also does bid on all nodes of the network.
=> add devnet.sh support for master branch, upgrade lint and test consensus with multiple bidders #580 

devnet.sh, harness/engine/profiles.go, pkg/config/consts.go, pkg/config/groups.go, pkg/config/loader.go, pkg/config/samples/default.dusk.toml, pkg/core/consensus/initiator/initiator.go
add option to configure consensustimeout as oposite of having hardcoded 5 seconds to enable testing it easily
=> add option to configure consensustimeout

pkg/util/legacy/conversions.go
=> Initialize the input being decoded in ruskInputsToInputs

devnet.sh, harness/engine/profiles.go, pkg/config/groups.go, pkg/core/candidate/broker.go, pkg/core/candidate/collector.go, pkg/core/chain/chain.go, pkg/core/chain/collectors.go, pkg/core/consensus/agreement/factory.go, pkg/core/consensus/bidautomaton/bidautomaton.go, pkg/core/consensus/candidate/blockgenerator.go, pkg/core/consensus/collector.go, pkg/core/consensus/initiator/initiator.go, pkg/core/consensus/reduction/firststep/aggregator.go, pkg/core/consensus/reduction/firststep/factory.go, pkg/core/consensus/reduction/firststep/reducer.go, pkg/core/consensus/reduction/secondstep/reducer.go, pkg/core/consensus/round.go, pkg/core/consensus/stakeautomaton/stakeautomaton.go, pkg/core/consensus/state.go, pkg/core/mempool/collector.go, pkg/core/mempool/mempool.go, pkg/gql/query/mempool.go, pkg/p2p/peer/processing/chainsync/counter.go, pkg/p2p/peer/processing/chainsync/sync.go, pkg/p2p/peer/responding/candidatebroker.go, pkg/p2p/peer/responding/datarequestor.go, pkg/p2p/peer/responding/roundresultbroker.go, pkg/p2p/wire/message/agreement.go, pkg/p2p/wire/message/message.go
closes #614
closes #607
closes #611
closes #612
=> Update NewCallbackListener for NewSafeCallbackListener in order to avoid race conditions on listeners #607

cmd/dusk/action.go, devnet.sh, harness/engine/profiles.go, pkg/config/groups.go, pkg/config/loader.go, pkg/config/samples/default.dusk.toml, pkg/core/chain/chain.go, pkg/core/consensus/bidautomaton/bidautomaton.go, pkg/core/consensus/bidautomaton/bidautomaton_test.go, pkg/core/consensus/candidate/blockgenerator.go, pkg/core/consensus/initiator/initiator.go, pkg/core/consensus/reduction/firststep/aggregator.go, pkg/core/consensus/stakeautomaton/stakeautomaton.go, pkg/core/consensus/stakeautomaton/stakeautomaton_test.go, pkg/gql/query/mempool.go, pkg/p2p/peer/processing/chainsync/sync.go, pkg/p2p/peer/responding/candidatebroker.go, pkg/p2p/peer/responding/datarequestor.go, pkg/p2p/peer/responding/roundresultbroker.go
=> Add option to configure rpcBus timeout #614

go.mod, pkg/api/handler_consensus_test.go, pkg/api/server.go, pkg/core/chain/chain.go, pkg/core/consensus/capi/api.go, pkg/core/consensus/capi/db.go, pkg/core/consensus/capi/model.go, pkg/core/consensus/capi/stormdb.go, pkg/core/consensus/round.go, pkg/p2p/peer/peer.go
Replace BoltDB queries with Storm #688
=> p2p/Peer should expose a endpoint to be queried that returns count of connected peers and detailed list of peers #680

Makefile, devnet.sh
=>  enable debug mode for devnet.sh scripts #675 

pkg/core/consensus/fixtures.go, pkg/core/consensus/phase.go, pkg/core/consensus/reduction/firststep/reduction_test.go, pkg/core/consensus/reduction/firststep/step.go, pkg/core/consensus/reduction/secondstep/reduction_test.go, pkg/core/consensus/reduction/secondstep/step.go, pkg/core/consensus/reduction/testutil.go, pkg/core/consensus/selection/selector_test.go, pkg/core/consensus/selection/step.go, pkg/core/loop/consensus.go, pkg/core/loop/consensus_test.go
=> Change the PhaseFn from function to interface so to ease logging in the consensus loop

cmd/voucher/action.go, cmd/voucher/flags.go, devnet.sh
* Add flags for Port and Hostname
* fix log file for rusk mock
=> Add flags to Voucher to bind to IP and Port #743

pkg/core/consensus/fixtures.go, pkg/core/consensus/phase.go, pkg/core/consensus/reduction/firststep/reduction_test.go, pkg/core/consensus/reduction/firststep/step.go, pkg/core/consensus/reduction/secondstep/reduction_test.go, pkg/core/consensus/reduction/secondstep/step.go, pkg/core/consensus/selection/selector_test.go, pkg/core/consensus/selection/step.go, pkg/core/loop/consensus.go, pkg/core/loop/consensus_test.go
=> Rename phase.Fn to phase.Initialize

pkg/core/consensus/selection/selector_test.go
=> Avoid concurrent access to selection testing table

cmd/dusk/server.go, pkg/p2p/peer/peer.go
=> Let caller of peer.Create handle errors

pkg/core/consensus/agreement/agreement_test.go, pkg/core/consensus/agreement/step.go, pkg/core/loop/consensus.go, pkg/core/loop/consensus_test.go
=> Add the candidate requestor to the Agreement

cmd/dusk/server.go, harness/engine/node.go, harness/engine/profiles.go, pkg/config/groups.go
=> Add a timeout context for establishing GRPC connections

cmd/dusk/server.go, go.sum
=> Reinstate automatons

cmd/dusk/server.go, pkg/core/data/ipc/transactions/provider.go, pkg/core/mempool/mempool.go, pkg/core/mempool/mempool_test.go
=> Use context cancellation in mempool, and remove shared context in mempool testing package

pkg/core/data/wallet/wallet.go
=> Change DUSK denomination from 8 to 10 decimals

pkg/core/transactor/listener.go
=> Store bid values when making bid transaction

pkg/p2p/peer/peer.go
=> Change 'trace message routing' log level to trace

cmd/dusk/server.go
=> Refine password entry flow

pkg/core/chain/chain.go, pkg/core/chain/sequencer.go, pkg/core/chain/synchronizer.go, pkg/core/chain/synchronizer_test.go
=> Add succeeding block to sequencer, if block was discarded

pkg/core/consensus/reduction/reduction.go, pkg/core/consensus/selection/step.go
=> Add step field to log entries for shouldProcess

cmd/dusk/server.go, pkg/core/mempool/mempool.go, pkg/p2p/peer/responding/databroker.go, pkg/p2p/peer/responding/databroker_test.go, pkg/p2p/peer/responding/ponger.go
=> Implement handlers for both topics.MemPool and topics.Pong

pkg/gql/httpserver.go, pkg/gql/httpserver_test.go, pkg/gql/notifications/broker.go, pkg/gql/notifications/client.go, pkg/gql/notifications/pool.go
=> Close websockets connections when they are not in use

pkg/rpc/client/client_test.go
=> Set a positive SessionDurationMins

harness/engine/profiles.go, harness/engine/utils.go, harness/tests/localnet_test.go, pkg/util/legacy/conversions.go
=>  Convert StandardType (3) to TransferType (0)

cmd/dusk/server.go, pkg/core/chain/chain.go, pkg/core/chain/chain_rc_test.go, pkg/core/chain/chain_test.go, pkg/core/chain/synchronizer.go, pkg/core/chain/synchronizer_test.go, pkg/core/consensus/agreement/agreement_test.go, pkg/core/consensus/agreement/step.go, pkg/core/loop/consensus.go, pkg/core/loop/consensus_test.go
=> Reintroduce synchronicity between the Synchronizer, Chain and Consensus loop

cmd/dusk/server.go, go.mod, go.sum, harness/tests/localnet_test.go, pkg/core/data/ipc/transactions/provider.go, pkg/core/transactor/listener.go, pkg/rpc/client/client.go, pkg/util/ruskmock/server.go
=> Support rusk.Wallet GetBalance grpc

cmd/wallet/conf/client.go, cmd/wallet/prompt/prompt.go, go.mod, go.sum, pkg/core/chain/chain.go, pkg/core/chain/chain_test.go, pkg/core/chain/synchronizer.go, pkg/core/chain/synchronizer_test.go
=> Move GetSyncProgress method back to the Chain

cmd/dusk/server.go, pkg/core/chain/chain.go, pkg/core/chain/chain_test.go, pkg/core/consensus/testing/node.go, pkg/core/transactor/transactor.go
=> Restrict outgoing stake transactions if node is not synced

CONTRIBUTING.md
=> Add coding convention to fail as soon as possible

pkg/core/verifiers.md, pkg/core/verifiers/README.md, pkg/core/verifiers/block.go
=> Update verifiers documentation

pkg/core/chain/chain.go
=> Ensure deadlock can not happen in acceptConsensusResults

cmd/dusk/server.go, go.mod, go.sum, pkg/config/groups.go, pkg/config/samples/default.dusk.toml, pkg/p2p/kadcast/router.go, pkg/p2p/kadcast/testing.go, pkg/p2p/peer/dupemap/dupemap.go, pkg/p2p/peer/dupemap/dupemap_test.go, pkg/p2p/peer/dupemap/tmpmap.go, pkg/p2p/peer/dupemap/tmpmap_test.go, pkg/p2p/peer/factory.go, pkg/p2p/peer/handshake_test.go, pkg/p2p/peer/peer_in_test.go, pkg/p2p/peer/peer_test.go, pkg/p2p/peer/responding/databroker.go, pkg/p2p/peer/responding/datarequestor.go
=> Secure `dupemap` against spam attacks

harness/engine/utils.go, harness/tests/localnet_test.go, pkg/core/chain/outsynctimer.go, pkg/core/chain/outsynctimer_test.go, pkg/core/chain/synchronizer.go, pkg/p2p/peer/peer.go
=> Implement outSyncTimer functionality in Synchronizer

Makefile, pkg/core/candidate/requestor.go, pkg/core/candidate/requestor_test.go, pkg/core/chain/chain.go, pkg/core/chain/chain_rc_test.go, pkg/core/chain/chain_test.go, pkg/core/chain/synchronizer.go, pkg/core/chain/synchronizer_test.go, pkg/core/consensus/agreement/agreement_test.go, pkg/core/consensus/publisher.go, pkg/core/mempool/mempool.go, pkg/core/mempool/mempool_test.go, pkg/p2p/peer/peer.go, pkg/p2p/peer/peer_test.go, pkg/p2p/peer/processor.go, pkg/p2p/peer/responding/blockhashbroker.go, pkg/p2p/peer/responding/blockhashbroker_test.go, pkg/p2p/peer/responding/candidatebroker.go, pkg/p2p/peer/responding/candidatebroker_test.go, pkg/p2p/peer/responding/databroker.go, pkg/p2p/peer/responding/databroker_test.go, pkg/p2p/peer/responding/datarequestor.go, pkg/p2p/peer/responding/datarequestor_test.go, pkg/p2p/peer/responding/ponger.go
=> Introduce PeerID to all MessageProcessor handlers

pkg/core/chain/chain.go, pkg/core/chain/synchronizer.go, pkg/core/chain/synchronizer_test.go
=> Lock Chain mutex when sync timer expires

cmd/utils/main.go, harness/engine/network.go, pkg/util/legacy/conversions.go, pkg/util/ruskmock/server.go
=> Add comprehensive logging to the RUSK mock server

harness/engine/profiles.go, pkg/util/legacy/conversions.go, pkg/util/ruskmock/server.go
=> Assign correct type id to Transfer Tx

cmd/dusk/server.go, pkg/config/groups.go, pkg/config/samples/default.dusk.toml, pkg/core/consensus/testing/utils.go, pkg/p2p/peer/dupemap/dupemap.go, pkg/p2p/peer/dupemap/dupemap_test.go, pkg/p2p/peer/dupemap/tmpmap.go, pkg/p2p/peer/dupemap/tmpmap_test.go, pkg/p2p/peer/processor.go, pkg/p2p/peer/responding/databroker.go, pkg/p2p/peer/responding/datarequestor.go, pkg/p2p/peer/responding/datarequestor_test.go
=> Introduce TTL property to Cucko Filter instance per round

go.sum, pkg/core/data/ipc/transactions/transaction.go, pkg/gql/README.md, pkg/gql/query/transactions.go, pkg/gql/query/transactions_test.go, pkg/gql/query/types.go
=> Add gas limit and gas price fields to tx queries

pkg/core/data/ipc/transactions/fixtures.go, pkg/core/mempool/mempool_test.go
=> Add BencmarkProcessTx tests

go.sum, pkg/core/data/ipc/transactions/transaction.go, pkg/gql/README.md, pkg/gql/query/blocks.go, pkg/gql/query/blocks_test.go, pkg/gql/query/types.go
=> Add fields for total reward and fees paid for block headers

pkg/gql/README.md, pkg/gql/httpserver.go, pkg/gql/httpserver_test.go
=> Use wss endpoint on TLS enabled

pkg/core/chain/chain.go
=> Ensure highestSeen is updated when a block is received from consensus

Makefile, go.mod, go.sum, harness/engine/utils.go, harness/tests/localnet_test.go
=> Measure network TPS 

harness/engine/utils.go
=> Remove GracefulClose call in utils methods

cmd/utils/main.go, cmd/utils/tps/tps.go
=> Add a utility which continually spams transactions from a node

harness/engine/profiles.go
=> Decrease default log level in test-harness

pkg/core/consensus/blockgenerator/candidate/blockgenerator.go, pkg/p2p/wire/protocol/frame.go
=> Increase block and p2p-based limits for transaction processing

pkg/core/mempool/mempool.go, pkg/core/transactor/listener.go
=> Concurrently process transaction sends in the mempool

go.sum, pkg/core/mempool/hashmap.go, pkg/core/mempool/interface.go, pkg/core/mempool/mempool.go
=> Alleviate bottleneck in removeAccepted

pkg/config/genesis/presets.go
=> Add the config name to the error message

go.mod, go.sum
=> Bump wallet version

cmd/dusk/server.go, harness/engine/network.go, harness/engine/node.go, harness/engine/profiles.go, harness/engine/utils.go, harness/tests/localnet_test.go, pkg/util/ruskmock/server.go
=> Enable unix transport for Rusk service

pkg/core/mempool/mempool.go
As discussed with goshawk-3, having a mempool grow
beyond its maximum capacity should be an indicator that
we should be looking at improving TPS. So for now, this
adjustment should be an adequate fix.
Fixes #1024
=> Drop transactions if the mempool reaches max capacity

.github/workflows/dusk_ci.yml, Makefile, pkg/p2p/kadcast/README.md, pkg/p2p/kadcast/basereader.go, pkg/p2p/kadcast/writer.go, pkg/p2p/peer/peer.go, pkg/p2p/peer/processor.go, pkg/p2p/wire/topics/topics.go
fixes #1033 
As a result from this PR, new github action has been added - `Continuous Integration / test-harness-kadcast`. It's goal is to continuously retest dusk network/consensus with Kadcast+RCUDP enabled.
=> Introduce point-to-point messaging in Kadcast

devnet.sh
How to test:
Terminal 1: `./devnet.sh -q 3 -r true -b true -d true`
Terminal 2: `make build && ./bin/utils metrics`
Terminal 3: `watch "curl http://localhost:9099/metrics`
closes: https://github.com/dusk-network/dusk-blockchain/issues/1036
=> update devnet script

cmd/utils/grpcclient/automatonservice.go, cmd/utils/main.go
In order to try to address issue reported on #1035 , I decided to see if increasing the timeouts would be of any help.
* add option to configure automate job stake and bid timeout request calls to provisioner and blockgenerator in order to figure out if this helps to address the issue
Please let me know where else could I look.
=> attempt to debug & fix #1035 

pkg/core/consensus/comms.go, pkg/core/consensus/selection/step.go
=> Integrate topics.Score propagation into Kadcast network

devnet.sh
How to test:
Terminal 1: ./devnet.sh -q 3 -r true -b true -d true -a true
Terminal 2: make build && ./bin/utils metrics
Terminal 3: watch "curl http://localhost:9099/metrics
Check logs and make sure there are no errs such as: `rpc error: code = Unauthenticated desc = token not provided`
=> Add automaton to devnet.sh and fix sendbid tx

harness/tests/localnet_test.go, pkg/core/mempool/mempool.go
=> Solve incomplete transaction propagation in kadcast

pkg/core/mempool/mempool.go
=> Use a ticker, instead of time.After, for mempool idling

pkg/util/nativeutils/rpcbus/rpcbus.go
=> Clean up timer resources properly when using RPCBus

pkg/p2p/kadcast/encoding/header.go, pkg/p2p/kadcast/maintainer.go, pkg/p2p/kadcast/network_test.go, pkg/p2p/kadcast/udpreader.go, pkg/p2p/kadcast/utils.go, pkg/p2p/kadcast/utils_test.go, pkg/p2p/kadcast/writer.go, pkg/util/nativeutils/rcudp/packet.go, pkg/util/nativeutils/rcudp/packet_test.go, pkg/util/nativeutils/rcudp/reader.go, pkg/util/nativeutils/rcudp/writer.go
=> Optimize broadcast implementation in kadcast

pkg/core/consensus/queue.go, pkg/core/loop/consensus.go, pkg/core/loop/consensus_test.go
=> Ensure queues are cleaned up properly after each round

pkg/p2p/kadcast/basereader.go, pkg/p2p/kadcast/tcpreader.go, pkg/p2p/kadcast/writer.go, pkg/util/nativeutils/rcudp/config.go, pkg/util/nativeutils/rcudp/packet.go, pkg/util/nativeutils/rcudp/packet_test.go, pkg/util/nativeutils/rcudp/reader.go, pkg/util/nativeutils/rcudp/writer.go
=> Integrate Height byte field into UDP packet

pkg/p2p/peer/connector.go, pkg/p2p/peer/peer.go
=> Reduce frequency at which the StormDB is called

pkg/p2p/wire/protocol/protocol.go
=> Set version tag to 0.4.3

go.mod, go.sum, pkg/p2p/kadcast/writer.go, pkg/p2p/peer/peer.go, pkg/p2p/peer/processor.go, pkg/util/container/ring/buffer.go, pkg/util/container/ring/buffer_test.go, pkg/util/container/ring/consumer.go, pkg/util/nativeutils/eventbus/eventbus_test.go, pkg/util/nativeutils/eventbus/listener.go, pkg/util/nativeutils/eventbus/mock.go
fixes #1069 
fixes #1087
fixes #1089
=> Extend ring buffer and Kadcast Writer

devnet.sh, harness/engine/node.go, harness/engine/profiles.go, pkg/config/samples/default.dusk.toml
=> Extend contract timeout to account for potential hangs

cmd/dusk/server.go, harness/engine/network.go, harness/tests/localnet_test.go, pkg/config/consts.go, pkg/core/candidate/requestor.go, pkg/core/consensus/agreement/agreement_test.go, pkg/core/consensus/agreement/step.go, pkg/core/consensus/comms.go, pkg/core/consensus/reduction/firststep/step.go, pkg/core/consensus/reduction/reduction.go, pkg/core/consensus/reduction/secondstep/step.go, pkg/core/consensus/selection/step.go, pkg/core/consensus/testing/utils.go, pkg/p2p/kadcast/writer.go, pkg/p2p/peer/peer.go, pkg/p2p/peer/processor.go, pkg/p2p/wire/message/message.go, pkg/util/nativeutils/eventbus/mock.go
=> Publish Reduction and Agreement messages in Kadcast 

pkg/core/consensus/reduction/aggregator.go, pkg/core/consensus/testing/utils.go, pkg/util/nativeutils/sortedset/sortedset.go, pkg/util/nativeutils/sortedset/sortedset_test.go
fixes #1105 
fixes #1099 
fixes #1108
=> Discard duplicated votes from a single Provisioner

cmd/dusk/action.go, harness/engine/profiles.go, pkg/core/consensus/agreement/handler.go, pkg/core/consensus/committee/handler.go, pkg/core/consensus/reduction/aggregator.go, pkg/core/consensus/reduction/firststep/step.go, pkg/core/consensus/reduction/secondstep/step.go, pkg/core/consensus/selection/step.go, pkg/core/consensus/user/provisioners.go, pkg/core/consensus/user/sortition.go, pkg/p2p/wire/message/reduction.go, pkg/util/nativeutils/sortedset/cluster.go, pkg/util/nativeutils/sortedset/sortedset.go, pkg/util/ruskmock/server.go, pkg/util/stringify.go
=> Improve consensus implementation traceability 

pkg/core/consensus/agreement/step.go, pkg/core/consensus/queue.go, pkg/core/consensus/queue_test.go, pkg/core/consensus/reduction/reduction.go, pkg/core/consensus/selection/step.go
=> Limit max amount of messages in consensus queue

pkg/core/consensus/agreement/agreement_in_test.go, pkg/core/consensus/agreement/handler.go, pkg/core/consensus/reduction/handler.go, pkg/p2p/wire/message/reduction.go
=> Change quorum from 3/4ths to 2/3rds

pkg/core/mempool/hashmap.go
=> Prevent putting a transaction in the mempool twice

pkg/p2p/peer/dupemap/dupemap.go
=> Extend default dupemap timeout to 60s

cmd/dusk/server.go
=> Add retry procedure for contacting voucher

pkg/p2p/peer/dupemap/dupemap.go, pkg/p2p/peer/processor.go, pkg/p2p/peer/responding/datarequestor.go
=> Update expiryTime of topics.Inv dupemap

harness/engine/profiles.go, pkg/core/consensus/agreement/handler.go, pkg/core/consensus/comms.go, pkg/core/consensus/reduction/aggregator.go, pkg/core/consensus/reduction/firststep/step.go, pkg/core/consensus/reduction/secondstep/step.go, pkg/core/consensus/selection/step.go, pkg/p2p/peer/processor.go, pkg/p2p/peer/responding/datarequestor.go, pkg/p2p/wire/message/inventory.go, pkg/p2p/wire/message/reduction.go, pkg/util/diagnostics/profile.go, pkg/util/ruskmock/server.go
=> Reduce Consensus log size for Debug Level

logging.md, pkg/core/chain/chain.go, pkg/core/consensus/agreement/accumulator.go, pkg/core/consensus/agreement/handler.go, pkg/core/consensus/agreement/step.go, pkg/core/consensus/agreement/store_map.go
=> Update block finalization formula to agreement_message_{round,hash,iteration

cmd/dusk/server.go, pkg/core/chain/chain.go, pkg/core/chain/chain_rc_test.go, pkg/core/chain/chain_test.go, pkg/core/chain/consensus.go, pkg/core/chain/ledger.go, pkg/core/chain/synchronizer.go, pkg/core/chain/synchronizer_test.go, pkg/core/consensus/testing/consensus_test.go, pkg/util/nativeutils/eventbus/listener.go
=> Recover the Consensus loop if a successive Block acceptance fails

pkg/core/consensus/agreement/handler.go, pkg/core/consensus/agreement/handler_test.go
=> Mitigate Cgo overhead for ReconstructApk

pkg/core/chain/chain.go, pkg/core/consensus/agreement/accumulator.go, pkg/core/consensus/agreement/agreement_in_test.go, pkg/core/consensus/agreement/agreement_test.go, pkg/core/consensus/agreement/handler.go, pkg/core/consensus/agreement/handler_test.go, pkg/core/consensus/agreement/step.go, pkg/core/consensus/agreement/store.go, pkg/core/consensus/blockgenerator/candidate/blockgenerator.go, pkg/core/consensus/committee/handler.go, pkg/core/consensus/committee/handler_test.go, pkg/core/consensus/reduction/firststep/step.go, pkg/core/consensus/reduction/handler.go, pkg/core/consensus/reduction/secondstep/reduction_test.go, pkg/core/consensus/reduction/secondstep/step.go, pkg/core/consensus/reduction/testutil.go, pkg/core/consensus/selection/handler.go, pkg/core/consensus/selection/step.go, pkg/core/consensus/user/provisioners_test.go, pkg/core/consensus/user/sortition.go, pkg/core/consensus/user/sortition_test.go, pkg/core/verifiers/block.go, pkg/p2p/wire/message/agreement.go, pkg/util/ruskmock/server.go
=> Create sortition hash from Seed value

pkg/core/consensus/selection/step.go
=> Allow timer to expire before proceeding to the Reduction phase

cmd/dusk/server.go, pkg/core/chain/chain.go, pkg/core/chain/chain_test.go, pkg/core/chain/fallback.go, pkg/core/consensus/testing/node.go, pkg/core/data/block/block.go, pkg/core/data/block/block_test.go, pkg/core/verifiers/block.go
=> Implement fallback procedure upon blockchain fork corner case

pkg/p2p/testbed/README.md, pkg/p2p/testbed/cluster_test.go, pkg/p2p/testbed/kadcast_test.go
=> Create a testbed package to stress test kadcast protocol

pkg/p2p/kadcast/peer.go, pkg/p2p/kadcast/peer_test.go, pkg/p2p/kadcast/reader.go, pkg/p2p/kadcast/writer.go
=> Cancel both Reader and Writer with single context

Makefile, cmd/dusk/server.go, harness/engine/network.go, harness/engine/profiles.go, harness/tests/localnet_test.go, pkg/config/groups.go, pkg/p2p/kadcast/peer.go
fixes #1228 
fixes #1226  
```bash
cd `dusk-network/dusk-blockchain`
make DUSK_NETWORK_PROFILE=kadcast  DUSK_NETWORK_SIZE=10  test-harness-tps
```
tail -F /tmp/localnet-\*/node-90\*/rusk_stdout
=> Run test-harness with Kadcast Rust network

harness/engine/network.go, harness/engine/profiles.go, pkg/config/groups.go, pkg/config/samples/default.dusk.toml, pkg/p2p/kadcast/peer.go
=> Support dial timeout and unix domain network for kadcast grpc client

harness/engine/network.go, harness/engine/profiles.go, harness/tests/localnet_test.go, pkg/p2p/kadcast/peer.go
=> Enable test-harness running rusk with unix domain socket IPC

pkg/core/loop/consensus.go, pkg/util/nativeutils/eventbus/listener.go, pkg/util/nativeutils/eventbus/publisher.go
=> Disallow ChanListeners to report warnings on a suspended consensus

pkg/p2p/testbed/cluster_test.go, pkg/p2p/testbed/kadcast_test.go
Use env CLUSTER_CSV=<your_csv_path> to use it
Resolves #1243
=> Allow to launch testbed on a remote cluster

pkg/p2p/testbed/cluster_test.go, pkg/p2p/testbed/kadcast_test.go
=> Remote testbed verify truncated message

pkg/p2p/kadcast/writer.go
=> Reintroduce priority mapper in topics.Kadcast Collector

.github/workflows/dusk_ci.yml, Makefile
=> Reintroduce kadcast test harness

Makefile, pkg/core/consensus/agreement/handler.go, pkg/core/consensus/reduction/handler.go, pkg/core/consensus/selection/handler.go
=> Avoid copy the signature during verification

cmd/dusk/server.go, harness/engine/profiles.go, pkg/config/groups.go, pkg/config/samples/default.dusk.toml, pkg/core/chain/chain.go, pkg/core/mempool/buntdb.go, pkg/core/mempool/buntdb_test.go, pkg/core/mempool/hashmap.go, pkg/core/mempool/hashmap_test.go, pkg/core/mempool/interface.go, pkg/core/mempool/mempool.go, pkg/core/mempool/mempool_test.go, pkg/util/ruskmock/db.go
=> Initial implementation of BuntDB backend for Mempool

pkg/gql/README.md, pkg/gql/query/blocks.go, pkg/gql/query/mempool.go, pkg/gql/query/transactions.go, pkg/gql/query/types.go
=> Support blocktimestamp field in transactions query

pkg/core/mempool/mempool.go, pkg/p2p/kadcast/reader.go, pkg/p2p/kadcast/writer.go
=> Decrement kadcast height value on message receiving

cmd/dusk/loadkeys.go, cmd/dusk/server.go, pkg/config/groups.go, pkg/config/samples/default.dusk.toml, pkg/core/consensus/key/keys.go
=> Generate, store and load Consensus keys

go.mod, go.sum, pkg/core/consensus/key/keys.go, pkg/core/consensus/key/keys_test.go
See also dusk-network/rusk#504
=> Change the encryption schema for the consensus wallet

pkg/core/data/ipc/transactions/payload.go, pkg/core/data/ipc/transactions/payload_decoded.go, pkg/core/data/ipc/transactions/transaction.go, pkg/core/verifiers/block.go, pkg/p2p/wire/message/transactions_test.go
This is just the revert of d8dc635abdb65da7681f78664609c6c7b3d1f3d4
Once dusk-network/rusk#541 is closed, this should resolve #1287
=> Reduce the coinbase txs to 1

.github/workflows/dusk_ci.yml, Makefile, harness/engine/network.go, pkg/config/genesis/generation.go
Override state_root for tests
Change test_harness to use the downloaded state
=> Change state_root to be compatible with rusk

pkg/core/consensus/blockgenerator/candidate/blockgenerator.go
A block is produced only when either:
- there is a transaction in the Mempool
- a 3s timeout commences
Resolves #1293
=> Wait txs for being included in the block

pkg/config/consts.go
=> Change base dusk unit

pkg/gql/README.md, pkg/gql/query/blocks.go, pkg/gql/query/transactions.go, pkg/gql/query/transactions_test.go, pkg/gql/query/types.go
- Change FeePaid to GasSpent 
- Fix how the block reward is calculated
Resolves #1310
=> Change FeePaid to GasSpent

pkg/gql/query/blocks.go, pkg/gql/query/types.go
=> Fix reward and feesPaid in graphQL

pkg/core/data/ipc/transactions/provider.go
=> Check transaction GasLimit against block GasLimit

pkg/config/genesis/generation.go
Changed as per https://github.com/dusk-network/rusk/pull/618
=> Update state-root to be compliant with the new one generated

pkg/core/chain/chain.go, pkg/core/chain/chain_test.go, pkg/core/chain/fallback.go, pkg/core/data/ipc/transactions/fixtures.go, pkg/core/data/ipc/transactions/provider.go, pkg/core/verifiers/block.go
=> Introduce Contract Storage revert in Fallback procedure

pkg/gql/query/transactions.go, pkg/gql/query/types.go
=> Add `JSON` field to graphQL Transaction struct

harness/engine/network.go, harness/engine/profiles.go, harness/tests/localnet_test.go
=> Introduce DUSK_NETWORK_REUSE to instruct test-harness to reuse an existing state

pkg/config/groups.go, pkg/core/chain/chain.go, pkg/core/consensus/reduction/firststep/step.go, pkg/util/throttle.go
=> Throttle verifyFn in reduction_1 phase

pkg/gql/query/types.go
=> Change GasSpent and GasLimit to float

pkg/core/chain/chain.go, pkg/core/chain/chain_test.go, pkg/core/chain/fallback.go, pkg/core/data/ipc/transactions/fixtures.go, pkg/core/data/ipc/transactions/provider.go, pkg/core/database/heavy/transactions.go, pkg/core/database/interfaces.go, pkg/core/database/lite/transactions.go, pkg/gql/query/blocks.go, pkg/gql/query/types.go, pkg/p2p/kadcast/writer.go, pkg/p2p/wire/protocol/frame.go, pkg/p2p/wire/protocol/gossip.go
=> Revert multiple ephemeral blocks

pkg/core/candidate/requestor.go, pkg/core/candidate/requestor_test.go, pkg/core/candidate/validator.go, pkg/core/consensus/agreement/agreement_test.go, pkg/core/consensus/committee/handler.go, pkg/core/consensus/selection/step.go, pkg/p2p/wire/message/newblock.go
=> Ensure candidate block hash is equal to the BlockHash of the msg.header

cmd/utils/metrics/api.go, cmd/utils/metrics/model.go, go.mod, go.sum, pkg/config/consts.go, pkg/config/genesis/generation.go, pkg/core/candidate/validator.go, pkg/core/candidate/validator_test.go, pkg/core/consensus/blockgenerator/candidate/blockgenerator.go, pkg/core/data/block/block.go, pkg/core/data/block/header.go, pkg/core/mempool/mempool_test.go, pkg/core/tests/helper/block.go, pkg/core/verifiers/block.go, pkg/core/verifiers/block_test.go, pkg/gql/README.md, pkg/gql/query/blocks.go, pkg/gql/query/query_test.go, pkg/gql/query/types.go, pkg/p2p/wire.md, pkg/p2p/wire/encoding/miscdata.go, pkg/p2p/wire/message/block.go
Remove `header.TxRoot` and add `header.GeneratorBlsPubkey`
Resolves #1368
=> Include BlockGenerator into the header

pkg/core/chain/chain.go, pkg/core/consensus/reduction/firststep/step.go, pkg/core/consensus/reduction/reduction.go, pkg/core/consensus/reduction/secondstep/reduction_test.go, pkg/core/consensus/reduction/secondstep/step.go, pkg/core/consensus/selection/step.go, pkg/core/data/block/block.go, pkg/core/data/block/header.go, pkg/core/loop/consensus.go, pkg/p2p/wire/message/agreement.go, pkg/util/throttle.go
=> Call verify block prior to voting for a candidate block

go.mod, go.sum, harness/engine/network.go, pkg/api/handler_consensus_test.go, pkg/config/consts.go, pkg/core/chain/chain.go, pkg/core/chain/fallback.go, pkg/core/chain/loader.go, pkg/core/consensus/blockgenerator/candidate/blockgenerator.go, pkg/core/consensus/blockgenerator/candidate/generator_test.go, pkg/core/consensus/blockgenerator/candidate/genesis.go, pkg/core/consensus/blockgenerator/candidate/genesis_test.go, pkg/core/consensus/blockgenerator/candidate/mock.go, pkg/core/consensus/capi/model.go, pkg/core/consensus/comms.go, pkg/core/consensus/testing/utils.go, pkg/core/consensus/user/provisioners.go, pkg/core/consensus/user/sortition_test.go, pkg/core/data/ipc/transactions/fixtures.go, pkg/core/data/ipc/transactions/payload_decoded.go, pkg/core/data/ipc/transactions/provider.go, pkg/core/data/ipc/transactions/transaction.go, pkg/core/tests/helper/block.go, pkg/core/verifiers/block.go, pkg/gql/query/blocks.go, pkg/p2p/kadcast/peer_test.go, pkg/p2p/wire/message/transactions_test.go, pkg/util/legacy/conversions.go
=> Adapt to new stake contract

pkg/config/consts.go, pkg/p2p/kadcast/peer_test.go, pkg/p2p/kadcast/reader.go, pkg/p2p/kadcast/writer.go, pkg/p2p/wire.md
=> Decrement kadcast height at Kadcast Writer

pkg/config/consts.go, pkg/core/consensus/agreement/handler.go, pkg/core/consensus/blockgenerator/candidate/blockgenerator.go, pkg/core/consensus/reduction/handler.go, pkg/core/consensus/selection/handler.go, pkg/core/loop/consensus.go, pkg/core/verifiers/block.go
=> Check quorum per each reduction step on agreement msg verification

pkg/core/consensus/reduction/firststep/step.go, pkg/core/consensus/reduction/reduction.go, pkg/core/consensus/reduction/secondstep/step.go, pkg/p2p/wire/message/agreement.go
=> Skip verifyFn on vote sending if a verified hash is provided

.github/workflows/dusk_ci.yml, Makefile, harness/engine/utils.go, harness/tests/localnet_test.go, pkg/p2p/kadcast/peer.go
=> Test harness

pkg/core/consensus/reduction/firststep/step.go, pkg/core/consensus/reduction/reduction.go, pkg/core/consensus/reduction/secondstep/step.go
=> Queue my own vote to be registered locally

pkg/core/mempool/buntdb.go, pkg/core/mempool/hashmap.go, pkg/core/mempool/interface.go, pkg/core/mempool/mempool.go
=> Discard mempool transactions containing a nullifier already accepted

cmd/utils/metrics/api.go, pkg/gql/README.md, pkg/gql/query/blocks_test.go, pkg/gql/query/transactions.go, pkg/gql/query/transactions_test.go, pkg/gql/query/types.go
* Add ContractInfo
* Remove input/output
=> Improve GQL API

pkg/gql/README.md, pkg/gql/query/blocks.go, pkg/gql/query/blocks_test.go
=> GQL: fix wrong block reward

harness/engine/utils.go, pkg/config/consts.go, pkg/core/data/ipc/transactions/provider.go, pkg/p2p/kadcast/peer.go, pkg/p2p/kadcast/reader.go, pkg/p2p/kadcast/writer.go
=> Inject rusk's version into gRPC headers

pkg/gql/README.md, pkg/gql/query/transactions.go
Add `blocks` query fields (default to 10.000)
Resolves #1400
=> QGL: Search txs up to 10.000 blocks

CHANGELOG.md, pkg/config/consts.go
fixes #975 
Probably It'll be worth adding also details about both 0.5.0 and 0.4.0 versions
=> Update ChangeLog with 0.6.0 section

pkg/core/chain/chain.go, pkg/core/chain/fallback.go
=> Restore provisioners set upon a complete fallback

cmd/utils/metrics/model.go, pkg/config/consts.go, pkg/config/genesis/generation.go, pkg/core/chain/chain.go, pkg/core/consensus/blockgenerator/candidate/blockgenerator.go, pkg/core/data/block/header.go, pkg/core/database/testing/drivers_test.go, pkg/gql/README.md, pkg/gql/query/blocks.go, pkg/gql/query/blocks_test.go, pkg/gql/query/types.go, pkg/p2p/wire/message/block.go
=> Include block gas limit into header

CHANGELOG.md, pkg/core/chain/chain.go, pkg/core/chain/fallback.go, pkg/core/consensus/agreement/step.go, pkg/core/consensus/reduction/firststep/step.go, pkg/core/verifiers/block.go
fixes #1413 
fixes #1425 
fixes #1412
=> Detect if a received block originated from a fork

CHANGELOG.md, pkg/config/consts.go, pkg/core/candidate/requestor.go, pkg/core/candidate/requestor_test.go, pkg/core/consensus/agreement/agreement_test.go, pkg/p2p/peer/responding/candidatebroker.go
fixes #1359  (Implements Option_1)
=> Request candidate block from  arbitrary active nodes

cmd/deployer/deployer.go, cmd/dusk/action.go, cmd/dusk/server.go, cmd/dusk/setconfig.go, cmd/voucher/action.go, harness/engine/network.go, harness/engine/node.go, harness/engine/profiles.go, pkg/config/groups.go, pkg/config/loader.go, pkg/config/loader_test.go, pkg/config/samples/default.dusk.toml, pkg/core/consensus/comms.go, pkg/p2p/peer/connector.go, pkg/p2p/peer/handshake.go, pkg/p2p/peer/peer.go, pkg/p2p/peer/peer_in_test.go, pkg/p2p/peer/registry.go, pkg/p2p/peer/responding/challenge.go, pkg/p2p/wire/protocol/protocol.go, pkg/util/diagnostics/statcollector.go
=> Clean up deprecated dusk configurations

pkg/core/chain/chain.go, pkg/core/chain/loader.go, pkg/core/consensus/agreement/checkcert.go, pkg/core/consensus/agreement/handler.go, pkg/core/consensus/agreement/step.go, pkg/core/consensus/reduction/firststep/step.go, pkg/core/consensus/reduction/secondstep/step.go, pkg/core/consensus/selection/step.go
=> Check certificate of the winning block

CHANGELOG.md, pkg/core/chain/chain.go, pkg/core/consensus/agreement/step.go, pkg/core/consensus/reduction/reduction.go, pkg/core/consensus/selection/step.go, pkg/core/verifiers/block.go
fixes #1436 
NB Tested on devnet - verifyFn errors are reported only on essential problems.
=> Allow verifyFn to report errors correctly

pkg/core/chain/chain.go, pkg/core/chain/chain_test.go, pkg/core/chain/fallback.go
=> Verify block header before repropagating

pkg/core/consensus/blockgenerator/candidate/blockgenerator.go, pkg/core/consensus/blockgenerator/candidate/genesis.go, pkg/core/consensus/blockgenerator/candidate/mock.go
=> Remove deprecated committee keys from block generator

CHANGELOG.md, pkg/config/consts.go
- Update `NodeVersion` to `0.6.0`
- Update `CHANGELOG.md`
=> Release `0.6.0` version

.github/workflows/dusk_ci.yml, pkg/config/consts.go, pkg/config/genesis/config.go, pkg/config/genesis/generation.go, pkg/config/genesis/presets.go, pkg/core/chain/chain.go, pkg/core/chain/chain_test.go
=> Remove genesis checks

CHANGELOG.md, pkg/gql/README.md, pkg/gql/query/blocks.go, pkg/gql/query/mempool.go, pkg/gql/query/transactions.go, pkg/gql/query/types.go
=> Add GQL `blocksrange` filter to transaction query

pkg/config/consts.go, pkg/core/chain/chain.go, pkg/core/data/ipc/transactions/fixtures.go, pkg/core/data/ipc/transactions/provider.go
=> Fetch provisioners list from stake contract only if the list is updated

CHANGELOG.md, pkg/gql/README.md, pkg/gql/query/transactions.go, pkg/gql/query/types.go
=> Add `raw` field to the transaction

CHANGELOG.md, cmd/utils/metrics/model.go, pkg/config/genesis/generation.go, pkg/config/genesis/presets.go, pkg/core/candidate/validator.go, pkg/core/consensus/blockgenerator/candidate/blockgenerator.go, pkg/core/data/block/block.go, pkg/core/data/block/header.go, pkg/core/mempool/mempool_test.go, pkg/core/tests/helper/block.go, pkg/core/verifiers/block.go, pkg/core/verifiers/block_test.go, pkg/gql/query/blocks.go, pkg/gql/query/query_test.go, pkg/gql/query/types.go, pkg/p2p/wire/message/block.go
This is basically a partial revert of 22ee8a2f8985d890d880854c5734f51b6abc366d
Resolves #1499
=> Add transactions merkle tree root to the block header

pkg/core/consensus/user/sortition.go
=> Fix createSortitionHash description

pkg/core/consensus/user/sortition.go
=> Use config.DUSK in sortition

pkg/core/consensus/user/README.md, pkg/core/consensus/user/sortition.go
=> Fix extractCommitteeMember loop

CHANGELOG.md, pkg/core/data/ipc/transactions/provider.go, pkg/p2p/wire/message/transactions_test.go
=> Fix acceptance of txs with empty payload

.github/workflows/dusk_ci.yml, pkg/config/genesis/generation.go, pkg/config/genesis/presets.go, pkg/core/chain/chain.go, pkg/core/consensus/header/header.go, pkg/core/consensus/header/header_test.go, pkg/core/data/block/certificate.go, pkg/gql/query/transactions.go, pkg/p2p/wire/encoding/miscdata.go, pkg/p2p/wire/encoding/miscdata_test.go, pkg/p2p/wire/message/agreement.go
- Fix BLS signature bytes count
- Remove mocked txs from Genesis block
=> Fix rusk node compatibility

README.md
=> Update README with new Go Get behavior

README.md
=> Update README with Wallet and Rusk info
