pkg/eventmon/logger/logger.go
pkg/eventmon/logger/logger_test.go
pkg/eventmon/monitor/monitor.go
pkg/eventmon/monitor/monitor_test.go

This commit should prevent a possible deadlock of the logrus instance, which can be caused if the node monitoring component hangs for any reason and does not read incoming messages. When this keeps going, the buffer can fill up and subsequent writes will block until this buffer is cleared.
Because we write to the node monitoring component with a logrus hook, the associated mutex is acquired and not released for as long as the write operation hangs.

Prevent indefinite hangs when writing to the node monitoring UNIX socket

---

.travis.yml
pkg/core/consensus/agreement/agreement_in_test.go
pkg/core/consensus/agreement/agreement_test.go
pkg/core/consensus/agreement/broker.go
pkg/core/consensus/agreement/collector.go
pkg/core/consensus/reduction/reduction_test.go

Fixes #62. The fix for the bug caused a slight API change for the agreement component (reduction results come in through a channel now) and thus the test to reproduce the bug was slightly changed as a result, to remain functional. To check the test before the update, and to run it for yourself, revert the branch to commit `14ac6da`, and it should fail. The only notable change should be the way the reduction result is sent.

Fix race condition in the agreement component

---

pkg/core/chain/chain.go

- Logging level on failure to verify a block or certificate downgraded from error to warning, as it is not a severe issue. This should also prevent pollution of the monitoring error logs with errors that do not matter.
- Remove the pre-built blindbid binaries, as they don't belong in this repository. Pre-built blindbid binaries can be included in release tarballs instead.

Minor adjustments to codebase

---

cmd/main.go
pkg/p2p/kadcast/packet.go
pkg/p2p/kadcast/peer.go
pkg/p2p/kadcast/protocol.go
pkg/p2p/kadcast/router.go
pkg/p2p/kadcast/utils.go

The issue comes out from #141  and closes #180 
The protocol methods for the node have been refactored.
- Created polling methods for bootstrapping nodes and network discovery nodes.
- Refactored logger messages.
- Moved the logic away from the `protocol.go` methods and send it to the `router.go` polling methods. Which are blocking and await for the responses to `PING` and `FIND_NODES` messages.

Protocol methods refactoring.

---

pkg/core/consensus/round.go
pkg/core/consensus/round_test.go

Queue agreement events on a seperate queue which flushes on a round update

---

pkg/util/nativeutils/eventbus/eventbus.go
pkg/util/nativeutils/eventbus/subscriber.go

nitpick: `listenerMap` is concurrent-safe so busLock mutex looks redundant.

Remove EventBus busLock

---

pkg/core/mempool/mempool.go

Return an empty slice when transaction is not found on a GetMempoolTxs request

---

harness/engine/node.go
harness/engine/profiles.go
pkg/core/transactor/listener.go

Found on wallet-cli testing after creating new wallet:
```
INFO[0530] Handled GetTxHistory request                  prefix=transactor
panic: interface conversion: interface {} is bytes.Buffer, not *node.TxHistoryResponse
```

Respond with node.TxHistoryResponse instead of bytes.Buffer

---

pkg/config/groups.go
pkg/core/data/transactions/provider.go
pkg/core/data/wallet/wallet.go
pkg/core/data/wallet/wallet_test.go
pkg/core/transactor/funcs.go
pkg/core/transactor/listener.go

* Updated createFromSeed to loadWalletFromSeedPbAndVk and added pk transactions.PublicKey, vk transactions.ViewKey as arguments to avoid double round trip
* Save PublicKey and ViewKey inside loadWalletFromSeedPbAndVk after successfully calling  LoadFromSeed
* Update loadWallet to loadWalletFromPasswordAndLoadPkVk and save PublicKey and ViewKey into Wallet instance for further use
* Removed some code dups by reusing loadResponse func and updated its name to loadResponseFromPub
* Make use of arguments PublicKey and ViewKey returned by GenerateSecretKey into loadWalletFromSeedPbAndVk

Save/Retrieve PublicKey and ViewKey from .dat file in the Wallet#471

---

cmd/utils/main.go
cmd/utils/transactions/transactions.go

In order to monitor the Dusk blockchain transactions, we need to have a utils cmd that creates all sort of transactions
Start a Dusk node using test harness with keepalive flag enabled:
```
NETWORK_SIZE=3 DUSK_BLOCKCHAIN=${PWD}/bin/dusk DUSK_BLINDBID=${PWD}/bin/blindbid-linux-amd64 DUSK_SEEDER=${PWD}/bin/voucher DUSK_WALLET_PASS="password" go test -v --count=1 --test.timeout=0 ./harness/tests/... -args -enable -keepalive
```
```
make build && ./bin/utils transactions --txtype=consensus --amount=10 --locktime=10 --grpchost=unix:///tmp/localnet-560157350/node-9001/dusk-grpc.sock
```

Add utils CMD to cmd/utils to generate transactions #547 

---

cmd/wallet/conf/config.go
cmd/wallet/main.go

Added new flag to wallet cmd in order to allow for loading different dusk.toml
To be able to target multiple different nodes on testnet, this option will come in handy so we can target different nodes 
Start a dusk node with testharness and run:
```
make build && ./bin/wallet --configpath=/tmp/localnet-(replace the new ID here)/node-9000/
```

add configpath argument to the wallet cmd

---

Makefile
cmd/utils/main.go
cmd/utils/metrics/api.go
cmd/utils/metrics/metrics.go
cmd/utils/tps.sh
cmd/utils/transactions/transactions.go

* fix EffectiveBlockTime
* add tx encode
* fix send tx to send to self if not set
* fix BlockByNumber method to return also transactions
* update gql default port
* Script to be used on testnet that can target multiple nodes, initially via unix socket, but to be updated and handle remote grpc connections.
* Usage:
```
./cmd/utils/tps.sh -h
Usage: tps.sh
Optional command line arguments
-q <number>  -- Quantity to run. eg: 3
-i <number>  -- ID of node. eg: 146512053
-p <number>  -- PORT of node. eg: 9000
```
```
watch "./cmd/utils/tps.sh -q 4 -i 146512053 -p 8999"
```
1. Start a small network of nodes with test-harness keepalive
```
make get-blindbid 
make build
NETWORK_SIZE=3 DUSK_BLOCKCHAIN=${PWD}/bin/dusk DUSK_BLINDBID=${PWD}/bin/blindbid-linux-amd64 DUSK_SEEDER=${PWD}/bin/voucher …
```

Improvements for metrics cmd #549 

---

.gitignore
Makefile
cmd/utils/main.go
cmd/utils/walletutils/wallet.go
devnet.sh

New script to start a local dev net:
`make devnet`
New script to load wallet via cmd line:
`make build && ./bin/utils walletutils --grpchost unix://opt/gocode/src/github.com/dusk-network/dusk-blockchain/devnet/dusk_data/dusk0/dusk-grpc.sock --walletcmd loadwallet --walletpassword password`
closes: #568
closes: #566

Add script to facilitate devnet without test harness #566

---

pkg/util/legacy/conversions.go

This prevents an error which caused failures in ExecuteStateTransition.
Fixes #600

Initialize Signature struct before decoding it

---

pkg/core/consensus/reduction/firststep/aggregator.go
pkg/core/consensus/reduction/firststep/aggregator_test.go
pkg/core/consensus/reduction/firststep/reducer.go
pkg/core/consensus/reduction/firststep/reduction_test.go
pkg/core/consensus/reduction/firststep/testutil.go
pkg/core/consensus/reduction/reducer.go
pkg/core/consensus/reduction/reduction_test.go
pkg/core/consensus/reduction/secondstep/aggregator.go
pkg/core/consensus/reduction/secondstep/aggregator_test.go
pkg/core/consensus/reduction/secondstep/reducer.go
pkg/core/consensus/reduction/secondstep/reduction_test.go
pkg/core/consensus/reduction/timer.go
pkg/core/consensus/reduction/timer_test.go

This should fix a possible race condition between the timer
and the aggregator, who could previously both call 'Halt'
at the same time, causing consensus desyncs.
Fixes #565

Synchronize access to the 'Halt' method

---

pkg/core/consensus/reduction/firststep/reduction_test.go
pkg/core/consensus/reduction/firststep/testutil.go

rename few vars on testutil.go to use same convention as in NewHelper func

Increase timeout for TestFirstStep in order to avoid it failing sometimes on CI

---

cmd/dusk/server.go
pkg/api/server.go
pkg/core/consensus/capi/api.go
pkg/core/consensus/capi/model.go
pkg/p2p/peer/handshake_test.go
pkg/p2p/peer/peer.go
pkg/p2p/peer/peer_in_test.go
pkg/p2p/peer/peer_test.go
pkg/p2p/peer/peer_test_func.go

Add monitoring API to count connected peers #751
Peer method NewReader returns error, but error is always nil. Return err is checked and will panic if not nil wich makes no sense since it is always nil #750
How to test it:
1. Start a local cluster with devnet.sh with 4 peers
`/devnet.sh -q 3`
2. Curl the endpoint of Node 0 and observe 3 peers connected:
```
curl http://localhost:9490/p2p/count
{"count":3}
```
3. Kill node 3
```
ps -ef|grep dusk
kill - 9 (PID OF NODE 3 HERE)
```
4. Curl the endpoint of Node 0 and observe 2 peers connected
```
curl http://localhost:9490/p2p/count
{"count":2}
```

Add Peer connected stats, Remove useless logic from NewReader method 

---

cmd/dusk/server.go
go.sum
pkg/p2p/peer/factory.go
pkg/p2p/peer/handshake_test.go
pkg/p2p/peer/peer.go
pkg/p2p/peer/peer_in_test.go
pkg/p2p/peer/peer_test.go

This allows either goroutine to cancel the other
on an encountered error. This gives way
to more idiomatic management of these goroutines.
Fixes #761

Replace usage of exitChan for context in Peer

---

cmd/dusk/server.go
pkg/p2p/peer/factory.go
pkg/p2p/peer/handshake_test.go
pkg/p2p/peer/peer_in_test.go
pkg/p2p/peer/peer_test.go

This value would always be nil, and thus is unnecessary.
Fixes #750

Remove error return value from SpawnReader

---

cmd/dusk/server.go
devnet.sh

Add a case for reading password from a non-terminal stdin

---

docs/internal/zenhub.md

This document is for internal purposes only, and serves to homogenize the workflow on ZenHub in an effort to increase proper issue management, and to ensure an up-to-date view of the board at all times.
Fixes #849

Add a document describing ZenHub workflow

---

pkg/core/consensus/testing/consensus_test.go
pkg/core/consensus/testing/node.go

This fixes a bug, where some nodes would not
receive all messages properly, and cause TestConsensus to fail
over a panic when attempting to retrieve a candidate block
from the network. The panic occurs because there are no
CandidateBrokers initialized in this test, and thus the request
message falls on deaf ears. The upward propagation of the error
ultimately leads to a panic.
Fixes #866

Start consensus only after all nodes have been initialized

---

pkg/core/chain/chain.go
pkg/core/chain/chain_test.go
pkg/core/chain/synchronizer.go
pkg/core/chain/synchronizer_test.go

This prevents blocks from being dropped. In order to
avoid halting on errors that get stuck in the channel,
errors are now to include blocks as well, so that the
recipient can determine whether or not it is ok to
halt on that particular error, based on block height.
Fixes #876

Buffer sends on CatchBlockChan

---

cmd/dusk/server.go
cmd/dusk/setconfig.go
cmd/utils/grpcclient/client.go
cmd/utils/grpcclient/configservice.go
cmd/utils/main.go
cmd/utils/tps.sh
devnet.sh
docs/elk.md
go.mod
pkg/core/mempool/mempool.go

fixes #964 
Example usage:
```
./bin/utils setconfig --grpcaddr="unix:///tmp/dusk-node/dusk-grpc.sock" --configname="logger.level" --configvalue="info"
./bin/utils setconfig --grpcaddr="127.0.0.1:10506" --configname="logger.level" --configvalue="trace"
```

Implement node.ConfigService

---

pkg/gql/query/blocks_test.go

Remove usage of hardcoded tx hash in GQL block tests

---

pkg/p2p/wire/protocol/protocol.go

This was missed previously for the release of 0.4.0, hence
why it was changed from 0.3.0 instead
Fixes #987

Bump version to 0.4.1

---

cmd/dusk/server.go
go.sum
pkg/p2p/peer/peer.go
pkg/p2p/peer/peer_in_test.go
pkg/p2p/peer/peer_test.go

This is achieved by fully removing the errChan
and substituting it for another Context object, created
when the peer is started up. The cancellation of one
of the loops will cascade a cancellation in the other,
without any risk of panicking.
Fixes #1020

Remove potential panic on closed channel send when connection drops

---

cmd/utils/tps/tps.go
pkg/core/mempool/mempool.go

This PR also adds logging entries in the mempool which show the size of the mempool before and after processing blocks.
Fixes #940

Add UNIX prefix to TPS util address in case we're using UNIX sockets

---

pkg/p2p/kadcast/encoding/helpers.go
pkg/p2p/kadcast/encoding/peerinfo.go

* replace sha3 by blake2b on kadcast helpers and peerinfo

Use blake2b for computing chunk IDs instead of Sha3. #207

---

pkg/core/consensus/bidautomaton/bidautomaton.go
pkg/core/consensus/stakeautomaton/stakeautomaton.go
pkg/core/transactor/listener.go
pkg/core/transactor/transactor.go

in order to stop having timeout errs in automate bid and stake requests, I've added responses to the requests and this seems to clear the logs.
How to test:
run devnet with automate true
`./devnet.sh -q 3 -r true -b true -d true -a true`
Observe there are no timeout errs.

#1050 - add response to automaton requests

---

devnet.sh

How to test:
Terminal 1: `./devnet.sh -q 3 -r true -b true -d true -a true`
Terminal 2: `make build && ./bin/utils metrics`
Terminal 3: `watch "curl http://localhost:9099/metrics"`
Terminal 4: `watch "ps -ef |grep dusk"`
Check logs and make sure there are no errs and that there are four instances of Dusk, four instances of mockrusk, one instance of mock and one instance of voucher.

Fix devnet.sh #1079

---

pkg/core/consensus/agreement/accumulator.go
pkg/core/consensus/reduction/aggregator.go
pkg/core/consensus/reduction/secondstep/reduction_test.go
pkg/core/data/ipc/transactions/fixtures.go
pkg/p2p/peer/processor.go
pkg/p2p/wire/message/agreement.go
pkg/p2p/wire/message/agreement_in_test.go
pkg/p2p/wire/message/score.go
pkg/util/ruskmock/server.go

These items were not used at all, the step wasn't even unmarshaled.
This should get rid of our malformed point error, as it originated
in unmarshaling the APK, which now no longer exists on that message.
Fixes #271, fixes #1085

Remove APK and step from Agreement message

---

harness/engine/profiles.go
harness/engine/utils.go
harness/tests/localnet_test.go
pkg/config/groups.go
pkg/config/samples/default.dusk.toml
pkg/core/mempool/mempool.go

Support both rate limiter and pendingPropagation in mempool

---

cmd/dusk/server.go
pkg/core/mempool/mempool.go
pkg/gql/httpserver.go
pkg/gql/httpserver_test.go
pkg/p2p/kadcast/peer.go
pkg/p2p/kadcast/reader.go
pkg/util/nativeutils/eventbus/eventbus.go
pkg/util/nativeutils/eventbus/listener.go
pkg/util/nativeutils/eventbus/listenermap.go

fixes #1241 
- Cancel all goroutine loops (kadcast listener, consensus, mempool, chain, gossip read loop)
- Close non-cancelable components (db driver, gql server, eventbus)
- Cancel pending grpc client requests on state/network services.

Terminate gracefully all subsystems/components and pending grpc requests

---

pkg/core/chain/chain.go
pkg/core/data/block/block.go
pkg/core/data/ipc/transactions/fixtures.go
pkg/core/data/ipc/transactions/provider.go
pkg/core/data/ipc/transactions/transaction.go
pkg/core/data/txrecords/txrecords.go
pkg/core/database/heavy/transactions.go
pkg/core/database/utils/encoding.go
pkg/core/mempool/buntdb.go
pkg/core/mempool/buntdb_test.go
pkg/core/mempool/hashmap.go
pkg/core/mempool/hashmap_test.go
pkg/core/mempool/mempool.go
pkg/core/mempool/mempool_test.go
pkg/gql/query/blocks.go
pkg/gql/query/transactions.go

Populate graphql with transaction data

---

pkg/core/data/ipc/transactions/note.go
pkg/gql/query/blocks.go
pkg/p2p/wire/message/transactions_test.go

Decode transparent notes amount

---

pkg/p2p/wire/protocol/gossip.go

This is not going to remove the Magic from the protocol, because is still under review
it just avoid to propagate magic mismatch errors
See also #1294

Disable magic error propagation

---

pkg/config/consts.go
pkg/config/genesis/generation.go
pkg/core/consensus/blockgenerator/candidate/blockgenerator.go

Increase block time to 15secs
Update rusk state root

Artificially increase block time

---

pkg/core/data/ipc/transactions/provider.go

Remove Deadline context for Accept, Finalize and Persist rusk grpc calls

---

pkg/config/consts.go
pkg/config/groups.go
pkg/core/chain/chain.go
pkg/core/chain/consensus.go
pkg/core/data/ipc/transactions/provider.go

Throttle block acceptance on specified conditions

---

pkg/core/mempool.md
pkg/core/mempool/buntdb.go
pkg/core/mempool/buntdb_test.go
pkg/core/mempool/hashmap.go
pkg/core/mempool/hashmap_test.go
pkg/core/mempool/interface.go
pkg/core/mempool/mempool.go
pkg/core/mempool/mempool_test.go
pkg/util/nativeutils/eventbus/mock.go

Mempool should discard any transaction with repeated nullifier

---

pkg/core/consensus/agreement/step.go
pkg/core/consensus/fixtures.go
pkg/core/consensus/reduction/firststep/reduction_test.go
pkg/core/consensus/reduction/secondstep/reduction_test.go
pkg/core/consensus/reduction/secondstep/step.go
pkg/core/consensus/selection/selector_test.go

fixes #1383 
As a proof, single-node network is now able to reach quorum.
```json
{
"bitset": "1",
"event": "quorum_reached",
"hash": "cc6ae795b7...7c1ecc2105",
"level": "debug",
"msg": "",
"node_id": "7100",
"process": "consensus",
"provs": [
"BLS key: ada282d4c9...6ebe52046c, Stakes: [Value: 2000000000000000, Reward: 720000000000, Counter: 0, Eligibility: 0]"
],
"quorum_target": 1,
"round": 51,
"s_voted_c": [
"Key: ada282d4c9...6ebe52046c, Count: 1"
],
"s_voting_c": [
"Key: ada282d4c9...6ebe52046c, Count: 1"
],
"step": 6,
"time": "2022-05-17T10:17:54",
"total_votes": 1
}
```

Reduce wire messages needed for propagating and registering Agreement vote

---

CHANGELOG.md
pkg/config/consts.go
pkg/config/groups.go
pkg/config/loader.go
pkg/config/loader_test.go
pkg/core/chain/chain.go
pkg/core/consensus/blockgenerator/candidate/blockgenerator.go
pkg/core/consensus/blockgenerator/candidate/generator_test.go
pkg/core/consensus/blockgenerator/candidate/genesis.go
pkg/core/consensus/blockgenerator/candidate/mock.go
pkg/core/consensus/comms.go
pkg/core/data/ipc/transactions/provider.go

A new configuration entry has been added to the `State` config section.
If not specified, it default to `const.DefaultBlockGasLimit`
- Remove Registry initialization from `cfg.Load` method. That was overriding the default values set by `init` method
- Add test to check default values
Resolves #1418
Resolves #1419

Make `BlockGasLimit` configurable

---

cmd/dusk/server.go
pkg/config/consts.go
pkg/config/loader.go
pkg/core/chain/consensus.go

ConsensusTimeout is now initialized with DefaultConsensusTimeout (5 seconds) but can be overrode using the custom configuration
Resolves #1423

Fix consensus timeout configuration

---

pkg/core/chain/chain.go
pkg/core/consensus/comms.go
pkg/core/consensus/fixtures.go
pkg/core/consensus/phase.go
pkg/core/consensus/reduction/aggregator.go
pkg/core/consensus/reduction/asyncsend.go
pkg/core/consensus/reduction/firststep/reduction_test.go
pkg/core/consensus/reduction/firststep/step.go
pkg/core/consensus/reduction/reduction.go
pkg/core/consensus/reduction/secondstep/reduction_test.go
pkg/core/consensus/reduction/secondstep/step.go
pkg/core/consensus/reduction/testutil.go
pkg/core/consensus/selection/selector_test.go
pkg/core/consensus/selection/step.go
pkg/core/data/ipc/transactions/provider.go
pkg/core/loop/consensus.go
pkg/core/loop/consensus_test.go
pkg/p2p/wire/message/agreement.go
pkg/util/nativeutils/sortedset/sortedset.go

fixes #1441 
Additionally, another edge case will be addressed out of this PR (with issue https://github.com/dusk-network/dusk-blockchain/issues/1444)

Send reduction concurrently without blocking votes re-propagation

---

harness/engine/utils.go
pkg/core/chain/chain.go
pkg/core/consensus/reduction/reduction.go
pkg/core/consensus/selection/step.go

fixes #1443 
NB: No `newblock verification error` noticed on devnet since the two fixes have been deployed

Update getRoundUpdate method to return a deep copy

---

pkg/config/consts.go
pkg/core/candidate/requestor.go
pkg/core/chain/chain.go
pkg/core/chain/consensus.go
pkg/core/chain/ledger.go
pkg/core/chain/synchronizer.go
pkg/core/chain/synchronizer_test.go
pkg/core/consensus/agreement/agreement_in_test.go
pkg/core/consensus/agreement/step.go
pkg/core/consensus/comms.go
pkg/core/consensus/reduction/firststep/step.go
pkg/core/consensus/reduction/reduction.go
pkg/core/consensus/reduction/secondstep/step.go
pkg/core/consensus/selection/step.go
pkg/core/mempool/mempool.go
pkg/p2p/kadcast/peer_test.go
pkg/p2p/kadcast/reader.go
pkg/p2p/kadcast/writer/broadcast.go
pkg/p2p/kadcast/writer/sendmany.go
pkg/p2p/kadcast/writer/sendone.go
pkg/p2p/peer/peer.go
pkg/p2p/peer/processor.go
pkg/p2p/wire/message/message.go
pkg/p2p/wire/message/metadata.go
pkg/p2p/wire/message/transactions_test.go
pkg/util/container/ring/buffer.go
pkg/util/container/ring/consumer.go
pkg/util/nativeutils/eventbus/eventbus_test.go
pkg/util/nativeutils/eventbus/listener.go
pkg/util/nativeutils/eventbus/mock.go

- Replace the current `message.Header` bytes with a structured `message.Metadata`
- Remove redundant usages of `config.KadcastInitHeader`
Resolves #1452

Propagate message metadata

---

.github/workflows/dusk_ci.yml
harness/engine/network.go
pkg/core/chain/chain.go
pkg/core/data/ipc/transactions/fixtures.go

See also #1448 
Resolves #1470

Add log for missed block detection

---

CHANGELOG.md
pkg/config/consts.go

- Add `raw` field to GQL transaction object [#1481]
- Add `blocksrange` filter to GQL transaction lookup [#1468]
- Remove hardcoded genesis checks [#1464]
- Remove provisioners list updates at every block [#1479]

Release `0.6.1`

---

pkg/core/consensus/user/sortition.go

This PR adds/improves documentation of Deterministic Sortition code.
---
Resolves #1491

Improve Sortition Documentation

---

CHANGELOG.md
pkg/core/chain/chain.go
pkg/core/chain/chain_test.go
pkg/core/chain/fallback.go
pkg/core/consensus/agreement/checkcert.go
pkg/core/consensus/blockgenerator/candidate/blockgenerator.go
pkg/core/consensus/blockgenerator/candidate/genesis.go
pkg/core/consensus/blockgenerator/candidate/mock.go
pkg/core/data/block/certificate.go
pkg/core/data/block/header.go
pkg/core/verifiers/block.go
pkg/gql/query/blocks.go
pkg/p2p/wire/message/agreement.go
pkg/p2p/wire/message/block.go

This add `iteration` to the block header, including it into the hashed fields used to calculate the block hash
In addition, this PR remove `step` from block header certificate (since it's a duplicated info)
Resolves #1500

Add `Iteration` to block header

---

.github/workflows/dusk_ci.yml
go.mod
go.sum
pkg/config/consts.go
pkg/core/chain/chain.go
pkg/core/consensus/agreement/agreement_in_test.go
pkg/core/consensus/agreement/checkcert.go
pkg/core/consensus/agreement/handler.go
pkg/core/consensus/committee/handler.go
pkg/core/consensus/fixtures.go
pkg/core/consensus/reduction/aggregator_test.go
pkg/core/consensus/reduction/firststep/reduction_test.go
pkg/core/consensus/reduction/handler.go
pkg/core/consensus/reduction/secondstep/reduction_test.go
pkg/core/consensus/reduction/testutil.go
pkg/core/consensus/selection/handler.go
pkg/core/consensus/user/provisioners_test.go
pkg/core/consensus/user/sortition.go
pkg/core/consensus/user/sortition_test.go
pkg/core/verifiers/block.go
pkg/p2p/wire/message/agreement.go
pkg/rpc/server/session_test.go

This PR removes the CommitteeSize() function, which computed the committee `size` as the minimum between MaxCommitteeSize and the number of available provisioners.
As a result, it makes all functions simply use the constant MaxCommitteeSize as the committee size.
The PR also fixes several tests, whose behavior wrongly assumed a correlation between the number of provisioners and the committee size.
Resolves #1520

Use constant Committee Size
